USE da_projects;


GO
SELECT *
FROM   customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT   gender,
         SUM(purchase_amount) AS total_revenue
FROM     customer_behavior
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount
FROM   customer_behavior
WHERE  discount_applied = 'Yes'
       AND purchase_amount > (SELECT AVG(purchase_amount)
                              FROM   customer_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT   TOP 5 item_purchased,
               ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM     customer_behavior
GROUP BY item_purchased
ORDER BY avg_review_rating DESC;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT   shipping_type,
         ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM     customer_behavior
WHERE    shipping_type = 'Standard'
         OR shipping_type = 'Express'
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT   subscription_status,
         ROUND(AVG(purchase_amount), 2) AS avg_spend,
         ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM     customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT   TOP 5 item_purchased,
               CAST ((SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0.0 END) / COUNT(*)) * 100 AS DECIMAL (10, 2)) AS discount_usage_rate
FROM     customer_behavior
GROUP BY item_purchased
ORDER BY discount_usage_rate DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH     customer_type
AS       (SELECT customer_id,
                 CASE WHEN previous_purchases = 1 THEN 'New' WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' ELSE 'Loyal' END AS customer_segment
          FROM   customer_behavior)
SELECT   customer_segment,
         COUNT(*) AS number_of_customers
FROM     customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH   item_rank
AS     (SELECT   category,
                 item_purchased,
                 COUNT(*) AS times_purchased,
                 DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS ranking
        FROM     customer_behavior
        GROUP BY category, item_purchased)
SELECT category,
       item_purchased,
       times_purchased
FROM   item_rank
WHERE  ranking <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT   subscription_status,
         COUNT(*) AS total_customers
FROM     customer_behavior
WHERE    previous_purchases >= 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT   age_group,
         SUM(purchase_amount) AS total_revenue
FROM     customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Business Case & What-If Opportunity Sizing (For Product Spec)
WITH   order_stats
AS     (SELECT purchase_amount,
               discount_applied,
               PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY purchase_amount) OVER () AS median_aov
        FROM   customer_behavior
        WHERE  discount_applied = 'Yes')
SELECT MAX(median_aov) AS median_aov_threshold,
       CAST (ROUND((SUM(CASE WHEN purchase_amount < median_aov THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 1) AS FLOAT) AS pct_below_median,
       ROUND(SUM(CASE WHEN purchase_amount < median_aov THEN (median_aov - purchase_amount) * 0.25 ELSE 0 END), 2) AS simulated_rev_lift,
       ROUND((SUM(CASE WHEN purchase_amount < median_aov THEN (median_aov - purchase_amount) * 0.25 ELSE 0 END) * 100.0) / SUM(purchase_amount), 1) AS cohort_rev_lift_pct
FROM   order_stats;